name: uprise
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  lottie: ^2.6.0
  iconly: ^1.0.1
  carousel_slider: ^4.2.1
  utility_extensions:
    git:
      url: https://github.com/hamzali4642/utility_extensions
  country_picker: ^2.0.20
  country_code_picker: ^3.0.0
  device_preview: ^1.1.0

  #firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  audio_video_progress_bar: ^1.0.1
  google_sign_in: ^6.1.4
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  marquee: ^2.2.3
  email_validator: ^2.1.17
  http: ^0.13.0
  syncfusion_flutter_charts: ^22.2.9
  shared_preferences: ^2.2.0
  just_audio: ^0.9.34
  color: ^3.0.0
  intl: ^0.18.0
  get_time_ago: ^1.2.5
  pull_to_refresh: ^2.0.0
  flutter_google_places: ^0.3.0
  google_geocoding: ^0.2.0
  google_api_headers: ^1.5.0+1
  google_maps_flutter: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/avatar/
     - assets/instruments/
     - assets/map/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/OswaldRegular.ttf
          weight: 400
        - asset: assets/fonts/OswaldBold.ttf
          weight: 700
        - asset: assets/fonts/OswaldSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OswaldMedium.ttf
          weight: 500
        - asset: assets/fonts/OswaldLight.ttf
          weight: 300
        - asset: assets/fonts/OswaldExtraLight.ttf
          weight: 200
